---
.travis.yml:
  dist: xenial
  deploy: false
  docker_defaults:
    dist: xenial
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
    - set: debian-8
      collection: puppet5
    - set: debian-8
      collection: puppet6
    - set: debian-9
      collection: puppet5
    - set: debian-9
      collection: puppet6
    - set: ubuntu-1404
      collection: puppet5
    - set: ubuntu-1404
      collection: puppet6
    - set: ubuntu-1604
      collection: puppet5
    - set: ubuntu-1604
      collection: puppet6
    - set: ubuntu-1804
      collection: puppet5
    - set: ubuntu-1804
      collection: puppet6
  user: treydock
  secure: "IO62lobymYKodvhzyMdgRvFJy0CeU44FJvQ117TIFEY+M8PRCHwYJU3Ga+USQh1xtx/F8eG4ZKCgM3l7Fr8k3UTLf3CRQU0oGhYQGODk6SQeGvwaDOyOx0tbZ3OPEvXtB22QVMSqEs+kFtk8V9Tl4zSs4Hlr7FInHvojOa3XqI/5NIiOPNh4Upl0P7Nz8hnX6FFBOogFmfUiha763VC63RZMCh9odsAwyY4scHooLnABWoi0Uig6+Xrt37lUJXyNLMIsWJ4lDRlGUV46NXhFtQYxF2FeaA/kPyDbmsBtjtUdoVd1vWjfm7UMc+btMnATRN/HPusI9LVJ+FBr0mVFfmIXzaADvL1X14Ro6ftOi+4s6hMJbb83YIeno4An2cIBrRcbj15vRdG4jD19GDPY59/F0cYk1y40kjccECnztmS9rAabLWHVaF2oTo7nNZL4HILii3/PxNlSuy9cTDTw/Z4bx6cE0/JUyeBmS72WqFEmhhdCjFgsttdIOAO+zsIFInWAojLG1WfrpdktvO2HQpq0mZoYAaikgUSTw69GIfp3ZJd6YKTCzG81vEi3p7NOUsTW8rs4SsZyobi3yl+dlLu9DRJSn7ej7/PHnoo//SRMR7kHeq2vKBmhi5TzEIz5QoDL/8vPBCQbvtdm3bLJ5gCBz6+xZUgDPTsy+Fs2+hY="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
